# Generated by Django 4.2.2 on 2023-06-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
