# Generated by Django 4.2.2 on 2023-06-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('address',), 'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('name',), 'verbose_name_plural': 'Customers'},
        ),
    ]
