# Generated by Django 4.2.2 on 2023-06-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_options_alter_customer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
